[system]

;0:View;1:StroedProc
command_type=0

command_name=view_overtimestoragesample

aptio_ip=192.168.1.200

srm_nodeid=16

discard_run_date=1,2,3,4,5

discard_time_range=01:30-05:45,6800

loop_interval_time=4

max_wait_discard_count=3

max_onetime_select_discard_count=5

allow_srm_error_code=0000,SC05A,0E01,0E02,0E03,0E59,0E5A,0E70,0E71,0E72,0E73,0E12,0F05,0F07,0F0A,1E01




