[system]

;0:View;1:StroedProc
command_type=0

command_name=view_overtimestoragesample

aptio_ip=127.0.0.1

srm_nodeid=09

discard_run_date=1,2,3,4,5,6,7

discard_time_range=01:30-05:45,3800

loop_interval_time=3

max_wait_discard_count=2

max_onetime_select_discard_count=8

allow_srm_error_code=0000,0F0A,0E59,AAAA



